namespace Ametrin.Optional.Generator;

[Generator]
public sealed class TupleOperationsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            var header = new StringBuilder();

            header.AppendLine("""namespace Ametrin.Optional;""");
            header.AppendLine();
            header.AppendLine("""// This file is generated by Ametrin.Optional""");
            header.AppendLine("""#nullable enable""");
            header.AppendLine();

            var sb = new StringBuilder();
            sb.Append(header);

            sb.AppendLine("""
            public static class OptionTupleConsumeExtensions
            {
            """);

            Consume(sb, 2);
            Consume(sb, 3);
            Consume(sb, 4);
            Consume(sb, 5);

            sb.AppendLine("""
            }
            """);

            ctx.AddSource("OptionTuples.Consume.g.cs", sb.ToString());


            sb.Clear();
            sb.Append(header);

            sb.AppendLine("""
            public static class OptionTupleMapExtensions
            {
            """);

            Map(sb, 2);
            Map(sb, 3);
            Map(sb, 4);
            Map(sb, 5);

            sb.AppendLine("""
            }
            """);


            ctx.AddSource("OptionTuples.Map.g.cs", sb.ToString());


            sb.Clear();
            sb.Append(header);

            sb.AppendLine("""
            public static class OptionTupleMatchExtensions
            {
            """);

            Match(sb, 2);
            Match(sb, 3);
            Match(sb, 4);
            Match(sb, 5);

            sb.AppendLine("""
            }
            """);


            ctx.AddSource("OptionTuples.Match.g.cs", sb.ToString());
        });
    }

    private static void Consume(StringBuilder sb, int genericCount)
    {
        var generics = string.Join(", ", Enumerable.Range(1, genericCount).Select(i => $"T{i}"));
        var genericOptionValues = string.Join(", ", Enumerable.Range(1, genericCount).Select(i => $"option._value.Item{i}"));
        var genericResultValues = string.Join(", ", Enumerable.Range(1, genericCount).Select(i => $"result._value.Item{i}"));

        sb.AppendLine($$"""
            extension<{{generics}}>(Option<({{generics}})> option)
            {
                public Option Consume(Action<{{generics}}>? success = null, Action? error = null)
                {
                    if (option._hasValue)
                    {
                        success?.Invoke({{genericOptionValues}});
                    }
                    else
                    {
                        error?.Invoke();
                    }

                    return option._hasValue;
                }

                public Option Consume<TArg>(TArg arg, Action<{{generics}}, TArg>? success = null, Action<TArg>? error = null)
                    where TArg : allows ref struct
                {
                    if (option._hasValue)
                    {
                        success?.Invoke({{genericOptionValues}}, arg);
                    }
                    else
                    {
                        error?.Invoke(arg);
                    }

                    return option._hasValue;
                }
            }

            extension<{{generics}}>(Result<({{generics}})> result)
            {
                public ErrorState Consume(Action<{{generics}}>? success = null, Action<Exception>? error = null)
                {
                    if (result._hasValue)
                    {
                        success?.Invoke({{genericResultValues}});
                        return default;
                    }
                    else
                    {
                        error?.Invoke(result._error);
                        return result._error;
                    }
                }

                public ErrorState Consume<TArg>(TArg arg, Action<{{generics}}, TArg>? success = null, Action<Exception, TArg>? error = null)
                    where TArg : allows ref struct
                {
                    if (result._hasValue)
                    {
                        success?.Invoke({{genericResultValues}}, arg);
                        return default;
                    }
                    else
                    {
                        error?.Invoke(result._error, arg);
                        return result._error;
                    }
                }
            }
            
            extension<{{generics}}, E>(Result<({{generics}}), E> result)
            {
                public ErrorState<E> Consume(Action<{{generics}}>? success = null, Action<E>? error = null)
                {
                    if (result._hasValue)
                    {
                        success?.Invoke({{genericResultValues}});
                        return default;
                    }
                    else
                    {
                        error?.Invoke(result._error);
                        return result._error;
                    }
                }

                public ErrorState<E> Consume<TArg>(TArg arg, Action<{{generics}}, TArg>? success = null, Action<E, TArg>? error = null)
                    where TArg : allows ref struct
                {
                    if (result._hasValue)
                    {
                        success?.Invoke({{genericResultValues}}, arg);
                        return default;
                    }
                    else
                    {
                        error?.Invoke(result._error, arg);
                        return result._error;
                    }
                }
            }
        """);
    }

    private static void Map(StringBuilder sb, int genericCount)
    {
        var generics = string.Join(", ", Enumerable.Range(1, genericCount).Select(i => $"T{i}"));
        var genericOptionValues = string.Join(", ", Enumerable.Range(1, genericCount).Select(i => $"option._value.Item{i}"));
        var genericResultValues = string.Join(", ", Enumerable.Range(1, genericCount).Select(i => $"result._value.Item{i}"));

        sb.AppendLine($$"""
            extension<{{generics}}>(Option<({{generics}})> option)
            {
                public Option<R> Map<R>(Func<{{generics}}, R> selector)
                    => option._hasValue ? selector({{genericOptionValues}}) : Option.Error<R>();
                public Option<R> Map<R>(Func<{{generics}}, Option<R>> selector)
                    => option._hasValue ? selector({{genericOptionValues}}) : Option.Error<R>();

                public Option<R> Map<TArg, R>(TArg arg, Func<{{generics}}, TArg, R> selector)
                    where TArg : allows ref struct
                    => option._hasValue ? selector({{genericOptionValues}}, arg) : Option.Error<R>();
                public Option<R> Map<TArg, R>(TArg arg, Func<{{generics}}, TArg, Option<R>> selector)
                    where TArg : allows ref struct
                    => option._hasValue ? selector({{genericOptionValues}}, arg) : Option.Error<R>();
            }

            extension<{{generics}}>(Result<({{generics}})> result)
            {
                public Result<R> Map<R>(Func<{{generics}}, R> selector)
                    => result._hasValue ? selector({{genericResultValues}}) : result._error;
                public Result<R> Map<R>(Func<{{generics}}, Result<R>> selector)
                    => result._hasValue ? selector({{genericResultValues}}) : result._error;

                public Result<R> Map<TArg, R>(TArg arg, Func<{{generics}}, TArg, R> selector)
                    where TArg : allows ref struct
                    => result._hasValue ? selector({{genericResultValues}}, arg) : result._error;
                public Result<R> Map<TArg, R>(TArg arg, Func<{{generics}}, TArg, Result<R>> selector)
                    where TArg : allows ref struct
                    => result._hasValue ? selector({{genericResultValues}}, arg) : result._error;
            }

            extension<{{generics}}, E>(Result<({{generics}}), E> result)
            {
                public Result<R, E> Map<R>(Func<{{generics}}, R> selector)
                    => result._hasValue ? selector({{genericResultValues}}) : result._error;
                public Result<R, E> Map<R>(Func<{{generics}}, Result<R, E>> selector)
                    => result._hasValue ? selector({{genericResultValues}}) : result._error;

                public Result<R, E> Map<TArg, R>(TArg arg, Func<{{generics}}, TArg, R> selector)
                    where TArg : allows ref struct
                    => result._hasValue ? selector({{genericResultValues}}, arg) : result._error;
                public Result<R, E> Map<TArg, R>(TArg arg, Func<{{generics}}, TArg, Result<R, E>> selector)
                    where TArg : allows ref struct
                    => result._hasValue ? selector({{genericResultValues}}, arg) : result._error;
            }
        """);
    }
    
    private static void Match(StringBuilder sb, int genericCount)
    {
        var generics = string.Join(", ", Enumerable.Range(1, genericCount).Select(i => $"T{i}"));
        var genericOptionValues = string.Join(", ", Enumerable.Range(1, genericCount).Select(i => $"option._value.Item{i}"));
        var genericResultValues = string.Join(", ", Enumerable.Range(1, genericCount).Select(i => $"result._value.Item{i}"));

        sb.AppendLine($$"""
            extension<{{generics}}>(Option<({{generics}})> option)
            {
                public TResult Match<TResult>(Func<{{generics}}, TResult> success, Func<TResult> error)
                    => option._hasValue ? success({{genericOptionValues}}) : error();

                public TResult Match<TArg, TResult>(TArg arg, Func<{{generics}}, TArg, TResult> success, Func<TArg, TResult> error)
                    where TArg : allows ref struct
                    => option._hasValue ? success({{genericOptionValues}}, arg) : error(arg);
            }

            extension<{{generics}}>(Result<({{generics}})> result)
            {
                public TResult Match<TResult>(Func<{{generics}}, TResult> success, Func<Exception, TResult> error)
                    => result._hasValue ? success({{genericResultValues}}) : error(result._error);

                public TResult Match<TArg, TResult>(TArg arg, Func<{{generics}}, TArg, TResult> success, Func<Exception, TArg, TResult> error)
                    where TArg : allows ref struct
                    => result._hasValue ? success({{genericResultValues}}, arg) : error(result._error, arg);
            }

            extension<{{generics}}, TError>(Result<({{generics}}), TError> result)
            {
                public TResult Match<TResult>(Func<{{generics}}, TResult> success, Func<TError, TResult> error)
                    => result._hasValue ? success({{genericResultValues}}) : error(result._error);

                public TResult Match<TArg, TResult>(TArg arg, Func<{{generics}}, TArg, TResult> success, Func<TError, TArg, TResult> error)
                    where TArg : allows ref struct
                    => result._hasValue ? success({{genericResultValues}}, arg) : error(result._error, arg);
            }
        """);
    }
}
